export const Users = [
    {
        id:1,
        profilePicture: "person/1.jpg",
        username: "Julia Messi",
    },
    {
        id:2,
        profilePicture: "person/2.jpg",
        username: "Julia Benz",
    },
    {
        id:3,
        profilePicture: "person/3.jpg",
        username: "Anne Hathway",
    },
    {
        id:4,
        profilePicture: "person/4.jpg",
        username: "Maria Shwaz",
    },
    {
        id:5,
        profilePicture: "person/5.jpg",
        username: "Jessica Alba",
    },
    {
        id:6,
        profilePicture: "person/6.jpg",
        username: "Juliet Mackenzi",
    },
    {
        id:7,
        profilePicture: "person/7.jpg",
        username: "Rachel Weisz",
    },
    {
        id:8,
        profilePicture: "person/8.jpg",
        username: "Scarlett Johnson",
    },
    {
        id:9,
        profilePicture: "person/9.jpg",
        username: "Chloe Simnew",
    },
    {

        id:10,
        profilePicture: "person/10.jpg",
        username: "Mary Broenden",
    },
]
  
export const Posts = [
    {
        id: 1,
        desc: "Love you all, A beautifull place ever visited",
        photo: "post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        like:100,
        comment: 10,
    },
    {
        id: 2,
        photo: "post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        like:75,
        comment: 8,
    },
    {
        id: 3,
        desc: "ever visited",
        photo: "post/3.jpg",
        date: "35 mins ago",
        userId: 3,
        like:105,
        comment: 18,
    },
    {
        id: 4,
        desc: "finally visited",
        photo: "post/4.jpg",
        date: "55 mins ago",
        userId: 4,
        like:140,
        comment: 37,
    },
    {
        id: 5,
        desc: "This is it!",
        photo: "post/5.jpg",
        date: "2 hours ago",
        userId: 5,
        like:405,
        comment: 81,
    },
    {
        id: 6,
        desc: "Love you all, A beautifull place ever visited",
        photo: "post/6.jpg",
        date: "5 mins ago",
        userId: 6,
        like:88,
        comment: 43,
    },
    {
        id: 7,
        photo: "post/7.jpg",
        date: "15 mins ago",
        userId: 7,
        like:143,
        comment: 43,
    },
    {
        id: 8,
        desc: "ever visited",
        photo: "post/8.jpg",
        date: "35 mins ago",
        userId: 8,
        like:210,
        comment: 25,
    },
    {
        id: 9,
        desc: "finally visited",
        photo: "post/9.jpg",
        date: "55 mins ago",
        userId: 9,
        like:710,
        comment: 83,
    },
    {
        id: 10,
        desc: "This is it!",
        photo: "post/10.jpg",
        date: "2 hours ago",
        userId: 10,
        like:1000,
        comment: 100,
    },
]